#!/bin/bash
vercomp () {
    if [[ $1 == $2 ]]
    then
        return 0
    fi
    local IFS=.
    local i ver1=($1) ver2=($2)
    # fill empty fields in ver1 with zeros
    for ((i=${#ver1[@]}; i<${#ver2[@]}; i++))
    do
        ver1[i]=0
    done
    for ((i=0; i<${#ver1[@]}; i++))
    do
        if [[ -z ${ver2[i]} ]]
        then
            # fill empty fields in ver2 with zeros
            ver2[i]=0
        fi
        if ((10#${ver1[i]} > 10#${ver2[i]}))
        then
            return 1
        fi
        if ((10#${ver1[i]} < 10#${ver2[i]}))
        then
            return 2
        fi
    done
    return 0
}

parse-pom() {
    if [ ! -f "$1" ] ; then
        echo "$1 is not a file" 1>&2
        return 1
    fi
    xpath "$1" '/project/version/text()' 2>/dev/null | sed -e 's/-SNAPSHOT//' 
    if [ ${PIPESTATUS[0]} -ne 0 ] ; then
        return 1
    fi
}

parse-json() {
    if [ ! -f "$1" ] ; then
        echo "$1 is not a file" 1>&2
        return 1
    fi

    cat "$1" | python -c 'import json,sys;obj=json.load(sys.stdin);print obj["version"]' 
}

